//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InventoryDBEntities : DbContext
    {
        public InventoryDBEntities()
            : base("name=InventoryDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderType> OrderTypes { get; set; }
        public virtual DbSet<Product> Products { get; set; }
    
        public virtual ObjectResult<PR_Orders_SelectAll_Result> PR_Orders_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_Orders_SelectAll_Result>("PR_Orders_SelectAll");
        }
    
        public virtual ObjectResult<PR_Orders_SelectAllByDate_Result> PR_Orders_SelectAllByDate(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_Orders_SelectAllByDate_Result>("PR_Orders_SelectAllByDate", fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> PR_Customer_CountCustomers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PR_Customer_CountCustomers");
        }
    
        public virtual ObjectResult<PR_Customer_SelectAllPagination_Result> PR_Customer_SelectAllPagination(Nullable<int> pageNo, Nullable<int> pageSize)
        {
            var pageNoParameter = pageNo.HasValue ?
                new ObjectParameter("PageNo", pageNo) :
                new ObjectParameter("PageNo", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_Customer_SelectAllPagination_Result>("PR_Customer_SelectAllPagination", pageNoParameter, pageSizeParameter);
        }
    
        public virtual ObjectResult<PR_Customer_SearchByCustomerName_Result> PR_Customer_SearchByCustomerName(Nullable<int> pageNo, Nullable<int> pageSize, string searchText)
        {
            var pageNoParameter = pageNo.HasValue ?
                new ObjectParameter("PageNo", pageNo) :
                new ObjectParameter("PageNo", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var searchTextParameter = searchText != null ?
                new ObjectParameter("SearchText", searchText) :
                new ObjectParameter("SearchText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_Customer_SearchByCustomerName_Result>("PR_Customer_SearchByCustomerName", pageNoParameter, pageSizeParameter, searchTextParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> PR_Product_CountProducts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PR_Product_CountProducts");
        }
    
        public virtual ObjectResult<PR_Product_SearchByProductName_Result> PR_Product_SearchByProductName(Nullable<int> pageNo, Nullable<int> pageSize, string searchText)
        {
            var pageNoParameter = pageNo.HasValue ?
                new ObjectParameter("PageNo", pageNo) :
                new ObjectParameter("PageNo", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var searchTextParameter = searchText != null ?
                new ObjectParameter("SearchText", searchText) :
                new ObjectParameter("SearchText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_Product_SearchByProductName_Result>("PR_Product_SearchByProductName", pageNoParameter, pageSizeParameter, searchTextParameter);
        }
    
        public virtual ObjectResult<PR_Product_SelectAllPagination_Result> PR_Product_SelectAllPagination(Nullable<int> pageNo, Nullable<int> pageSize)
        {
            var pageNoParameter = pageNo.HasValue ?
                new ObjectParameter("PageNo", pageNo) :
                new ObjectParameter("PageNo", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_Product_SelectAllPagination_Result>("PR_Product_SelectAllPagination", pageNoParameter, pageSizeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> PR_Orders_CountOrders()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PR_Orders_CountOrders");
        }
    
        public virtual ObjectResult<PR_Orders_SelectAllPagination_Result> PR_Orders_SelectAllPagination(Nullable<int> pageNo, Nullable<int> pageSize, string direction)
        {
            var pageNoParameter = pageNo.HasValue ?
                new ObjectParameter("PageNo", pageNo) :
                new ObjectParameter("PageNo", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var directionParameter = direction != null ?
                new ObjectParameter("Direction", direction) :
                new ObjectParameter("Direction", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_Orders_SelectAllPagination_Result>("PR_Orders_SelectAllPagination", pageNoParameter, pageSizeParameter, directionParameter);
        }
    }
}
